name: first workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Setup
        run: make setup
      - name: Test
        run: make test
      - name: Lint
        run: make lint

