name: first workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    steps: 
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
      - name: Setup
        run: make setup
      - name: Test
        run: make test
      - name: Lint
        run: make lint

